# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pp_Design_v1.ui',
# licensing of 'pp_Design_v1.ui' applies.
#
# Created: Thu Jul 25 17:21:27 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1234, 842)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.cbAcademieSelect = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAcademieSelect.sizePolicy().hasHeightForWidth())
        self.cbAcademieSelect.setSizePolicy(sizePolicy)
        self.cbAcademieSelect.setObjectName("cbAcademieSelect")
        self.horizontalLayout_4.addWidget(self.cbAcademieSelect)
        self.pbAcademieAjout = QtWidgets.QPushButton(Form)
        self.pbAcademieAjout.setMinimumSize(QtCore.QSize(102, 0))
        self.pbAcademieAjout.setObjectName("pbAcademieAjout")
        self.horizontalLayout_4.addWidget(self.pbAcademieAjout)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cbEtablissementSelect = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbEtablissementSelect.sizePolicy().hasHeightForWidth())
        self.cbEtablissementSelect.setSizePolicy(sizePolicy)
        self.cbEtablissementSelect.setObjectName("cbEtablissementSelect")
        self.horizontalLayout_3.addWidget(self.cbEtablissementSelect)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setMinimumSize(QtCore.QSize(102, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cbClasseSelect = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbClasseSelect.sizePolicy().hasHeightForWidth())
        self.cbClasseSelect.setSizePolicy(sizePolicy)
        self.cbClasseSelect.setObjectName("cbClasseSelect")
        self.horizontalLayout.addWidget(self.cbClasseSelect)
        self.pb = QtWidgets.QPushButton(Form)
        self.pb.setMinimumSize(QtCore.QSize(102, 0))
        self.pb.setObjectName("pb")
        self.horizontalLayout.addWidget(self.pb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_10.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.twSaisieNote = QtWidgets.QTableWidget(self.tab)
        self.twSaisieNote.setGeometry(QtCore.QRect(290, 30, 871, 601))
        self.twSaisieNote.setObjectName("twSaisieNote")
        self.twSaisieNote.setColumnCount(2)
        self.twSaisieNote.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twSaisieNote.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twSaisieNote.setHorizontalHeaderItem(1, item)
        self.pvNoteAjout = QtWidgets.QPushButton(self.tab)
        self.pvNoteAjout.setGeometry(QtCore.QRect(680, 650, 75, 23))
        self.pvNoteAjout.setObjectName("pvNoteAjout")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(19, 50, 251, 291))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.cbMatiereSelect = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.cbMatiereSelect.setObjectName("cbMatiereSelect")
        self.verticalLayout_2.addWidget(self.cbMatiereSelect)
        self.pbMatiereAjout = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pbMatiereAjout.setObjectName("pbMatiereAjout")
        self.verticalLayout_2.addWidget(self.pbMatiereAjout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.leDevoirEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.leDevoirEdit.setObjectName("leDevoirEdit")
        self.verticalLayout.addWidget(self.leDevoirEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.dsbCoeffDevoir = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dsbCoeffDevoir.setObjectName("dsbCoeffDevoir")
        self.horizontalLayout_8.addWidget(self.dsbCoeffDevoir)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.twAffichageMoyennes = QtWidgets.QTableWidget(self.tab_2)
        self.twAffichageMoyennes.setGeometry(QtCore.QRect(20, 60, 551, 601))
        self.twAffichageMoyennes.setObjectName("twAffichageMoyennes")
        self.twAffichageMoyennes.setColumnCount(3)
        self.twAffichageMoyennes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twAffichageMoyennes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAffichageMoyennes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAffichageMoyennes.setHorizontalHeaderItem(4, item)
        self.wGraph = QtWidgets.QLabel(self.tab_2)
        self.wGraph.setGeometry(QtCore.QRect(670, 80, 391, 401))
        self.wGraph.setObjectName("wGraph")
        self.pbImpressionPdf = QtWidgets.QPushButton(self.tab_2)
        self.pbImpressionPdf.setGeometry(QtCore.QRect(710, 570, 151, 23))
        self.pbImpressionPdf.setObjectName("pbImpressionPdf")
        self.pbExportCsv = QtWidgets.QPushButton(self.tab_2)
        self.pbExportCsv.setGeometry(QtCore.QRect(920, 570, 151, 23))
        self.pbExportCsv.setObjectName("pbExportCsv")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Editeur de notes", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Académie", None, -1))
        self.pbAcademieAjout.setText(QtWidgets.QApplication.translate("Form", "Ajout / Modification", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Etablissement", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("Form", "Ajout / Modification", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Classe", None, -1))
        self.pb.setText(QtWidgets.QApplication.translate("Form", "Ajout  / Modification", None, -1))
        self.twSaisieNote.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Form", "Elève", None, -1))
        self.twSaisieNote.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Form", "Notes", None, -1))
        self.pvNoteAjout.setText(QtWidgets.QApplication.translate("Form", "Valider", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Matière", None, -1))
        self.pbMatiereAjout.setText(QtWidgets.QApplication.translate("Form", "Ajout", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Nom du devoir", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "Coefficient du devoir", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("Form", "Saisie des Notes", None, -1))
        # self.twAffichageMoyennes.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Form", "Elève", None, -1))
        # self.twAffichageMoyennes.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Form", "Matière1", None, -1))
        # self.twAffichageMoyennes.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Form", "Matière2", None, -1))
        self.wGraph.setText(QtWidgets.QApplication.translate("Form", "Diagramme radar", None, -1))
        self.pbImpressionPdf.setText(QtWidgets.QApplication.translate("Form", "Impression Bulletin pdf", None, -1))
        self.pbExportCsv.setText(QtWidgets.QApplication.translate("Form", "Exporter les notes en csv", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("Form", "Affichage des Moyennes par Matière", None, -1))

