# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/AELION/AppData/Local/Temp/PP_Design_v1EIeBhI.ui',
# licensing of 'C:/Users/AELION/AppData/Local/Temp/PP_Design_v1EIeBhI.ui' applies.
#
# Created: Thu Aug 15 18:30:13 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1192, 836)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(30, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.cbAcademieSelect = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAcademieSelect.sizePolicy().hasHeightForWidth())
        self.cbAcademieSelect.setSizePolicy(sizePolicy)
        self.cbAcademieSelect.setObjectName("cbAcademieSelect")
        self.horizontalLayout_4.addWidget(self.cbAcademieSelect)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cbEtablissementSelect = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbEtablissementSelect.sizePolicy().hasHeightForWidth())
        self.cbEtablissementSelect.setSizePolicy(sizePolicy)
        self.cbEtablissementSelect.setObjectName("cbEtablissementSelect")
        self.horizontalLayout_3.addWidget(self.cbEtablissementSelect)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cbClasseSelect = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbClasseSelect.sizePolicy().hasHeightForWidth())
        self.cbClasseSelect.setSizePolicy(sizePolicy)
        self.cbClasseSelect.setObjectName("cbClasseSelect")
        self.horizontalLayout.addWidget(self.cbClasseSelect)
        self.horizontalLayout_10.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.pbGestionDb = QtWidgets.QPushButton(Form)
        self.pbGestionDb.setObjectName("pbGestionDb")
        self.horizontalLayout_10.addWidget(self.pbGestionDb)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem4)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(660, 50, 481, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.qRadar = QtWidgets.QVBoxLayout()
        self.qRadar.setObjectName("qRadar")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.qRadar.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.qRadar)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem6)
        self.pbImpressionPdf = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbImpressionPdf.setObjectName("pbImpressionPdf")
        self.verticalLayout_5.addWidget(self.pbImpressionPdf)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem7)
        self.pbExportCsv = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pbExportCsv.setObjectName("pbExportCsv")
        self.verticalLayout_5.addWidget(self.pbExportCsv)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 621, 631))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.twAffichageMoyennes = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twAffichageMoyennes.sizePolicy().hasHeightForWidth())
        self.twAffichageMoyennes.setSizePolicy(sizePolicy)
        self.twAffichageMoyennes.setObjectName("twAffichageMoyennes")
        self.twAffichageMoyennes.setColumnCount(0)
        self.twAffichageMoyennes.setRowCount(0)
        self.twAffichageMoyennes.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_6.addWidget(self.twAffichageMoyennes)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.twSaisieNote = QtWidgets.QTableWidget(self.tab)
        self.twSaisieNote.setGeometry(QtCore.QRect(380, 40, 771, 601))
        self.twSaisieNote.setObjectName("twSaisieNote")
        self.twSaisieNote.setColumnCount(0)
        self.twSaisieNote.setRowCount(0)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 40, 331, 601))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(130, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.cbMatiereSelect = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.cbMatiereSelect.setObjectName("cbMatiereSelect")
        self.horizontalLayout_2.addWidget(self.cbMatiereSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(130, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.leDevoirEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.leDevoirEdit.setObjectName("leDevoirEdit")
        self.horizontalLayout_6.addWidget(self.leDevoirEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(125, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.dsbCoeffDevoir = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_5)
        self.dsbCoeffDevoir.setObjectName("dsbCoeffDevoir")
        self.horizontalLayout_8.addWidget(self.dsbCoeffDevoir)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.pbNoteAjout = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pbNoteAjout.setObjectName("pbNoteAjout")
        self.verticalLayout.addWidget(self.pbNoteAjout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(130, 0))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.cbMatiereSelect_4 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.cbMatiereSelect_4.setObjectName("cbMatiereSelect_4")
        self.horizontalLayout_13.addWidget(self.cbMatiereSelect_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(130, 0))
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_15.addWidget(self.label_21)
        self.cbMatiereSelect_5 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.cbMatiereSelect_5.setObjectName("cbMatiereSelect_5")
        self.horizontalLayout_15.addWidget(self.cbMatiereSelect_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(130, 0))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.leDevoirEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.leDevoirEdit_3.setObjectName("leDevoirEdit_3")
        self.horizontalLayout_14.addWidget(self.leDevoirEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_19.setMinimumSize(QtCore.QSize(125, 0))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.dsbCoeffDevoir_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_5)
        self.dsbCoeffDevoir_3.setObjectName("dsbCoeffDevoir_3")
        self.horizontalLayout_12.addWidget(self.dsbCoeffDevoir_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.pbMatiereSuppr_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pbMatiereSuppr_3.setObjectName("pbMatiereSuppr_3")
        self.verticalLayout_2.addWidget(self.pbMatiereSuppr_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(130, 0))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24)
        self.cbMatiereSelectSuppr = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.cbMatiereSelectSuppr.setObjectName("cbMatiereSelectSuppr")
        self.horizontalLayout_17.addWidget(self.cbMatiereSelectSuppr)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(130, 0))
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.cbMatiereSelectDevoirSuppr = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.cbMatiereSelectDevoirSuppr.setObjectName("cbMatiereSelectDevoirSuppr")
        self.horizontalLayout_19.addWidget(self.cbMatiereSelectDevoirSuppr)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.pbDevoirSuppr = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pbDevoirSuppr.setObjectName("pbDevoirSuppr")
        self.verticalLayout_7.addWidget(self.pbDevoirSuppr)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.verticalLayout_10.addLayout(self.verticalLayout_3)
        self.label_98 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_10.addWidget(self.label_98)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_4.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Editeur de notes", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Académie", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Etablissement", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Classe", None, -1))
        self.pbGestionDb.setText(QtWidgets.QApplication.translate("Form", "Gestion des Académies, Etablissements, Classes, Eleves et Matières", None, -1))
        self.pbImpressionPdf.setText(QtWidgets.QApplication.translate("Form", "Impression Bulletin pdf", None, -1))
        self.pbExportCsv.setText(QtWidgets.QApplication.translate("Form", "Exporter les notes en csv", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Moyenne par Elève par Matière", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("Form", "Affichage des Moyennes par Matière", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Form", "Ajout devoir", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Matière *", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Nom du devoir *", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "Coefficient du devoir *", None, -1))
        self.pbNoteAjout.setText(QtWidgets.QApplication.translate("Form", "Ajout", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("Form", "Modification devoir", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Form", "Matière *", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Form", "Nom du devoir *", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Form", "Nouveau nom du devoir *", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Form", "Coefficient du devoir *", None, -1))
        self.pbMatiereSuppr_3.setText(QtWidgets.QApplication.translate("Form", "Modification", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "Suppression devoir", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("Form", "Matière *", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("Form", "Nom du devoir *", None, -1))
        self.pbDevoirSuppr.setText(QtWidgets.QApplication.translate("Form", "Suppression", None, -1))
        self.label_98.setText(QtWidgets.QApplication.translate("Form", "* Champs obligatoires", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("Form", "Saisie des Notes", None, -1))

