# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/AELION/AppData/Local/Temp/pp_Design_v2KPRtFq.ui',
# licensing of 'C:/Users/AELION/AppData/Local/Temp/pp_Design_v2KPRtFq.ui' applies.
#
# Created: Fri Aug  9 17:53:32 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form_W2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(673, 668)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 1174, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 651, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(10, 10, 321, 531))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem)
        self.label_141 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.label_141.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_141.setFont(font)
        self.label_141.setObjectName("label_141")
        self.verticalLayout_11.addWidget(self.label_141)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_145 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.label_145.setMinimumSize(QtCore.QSize(110, 0))
        self.label_145.setObjectName("label_145")
        self.horizontalLayout_42.addWidget(self.label_145)
        self.BDleAcaAjoutNom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_16)
        self.BDleAcaAjoutNom.setObjectName("BDleAcaAjoutNom")
        self.horizontalLayout_42.addWidget(self.BDleAcaAjoutNom)
        self.verticalLayout_11.addLayout(self.horizontalLayout_42)
        self.BDpbAcaAjoutValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_16)
        self.BDpbAcaAjoutValid.setObjectName("BDpbAcaAjoutValid")
        self.verticalLayout_11.addWidget(self.BDpbAcaAjoutValid)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.label_147 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_147.setFont(font)
        self.label_147.setObjectName("label_147")
        self.verticalLayout_11.addWidget(self.label_147)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_148 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.label_148.setMinimumSize(QtCore.QSize(110, 0))
        self.label_148.setObjectName("label_148")
        self.horizontalLayout_44.addWidget(self.label_148)
        self.BDcbAcaModifSelectNom = QtWidgets.QComboBox(self.horizontalLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbAcaModifSelectNom.sizePolicy().hasHeightForWidth())
        self.BDcbAcaModifSelectNom.setSizePolicy(sizePolicy)
        self.BDcbAcaModifSelectNom.setObjectName("BDcbAcaModifSelectNom")
        self.horizontalLayout_44.addWidget(self.BDcbAcaModifSelectNom)
        self.verticalLayout_11.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_149 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.label_149.setMinimumSize(QtCore.QSize(110, 0))
        self.label_149.setObjectName("label_149")
        self.horizontalLayout_45.addWidget(self.label_149)
        self.BDleAcaModifNom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_16)
        self.BDleAcaModifNom.setObjectName("BDleAcaModifNom")
        self.horizontalLayout_45.addWidget(self.BDleAcaModifNom)
        self.verticalLayout_11.addLayout(self.horizontalLayout_45)
        self.BDpbAcaModifValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_16)
        self.BDpbAcaModifValid.setObjectName("BDpbAcaModifValid")
        self.verticalLayout_11.addWidget(self.BDpbAcaModifValid)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.label_156 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_156.setFont(font)
        self.label_156.setObjectName("label_156")
        self.verticalLayout_11.addWidget(self.label_156)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_158 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.label_158.setMinimumSize(QtCore.QSize(110, 0))
        self.label_158.setObjectName("label_158")
        self.horizontalLayout_52.addWidget(self.label_158)
        self.BDcbAcaSupprSelectNom = QtWidgets.QComboBox(self.horizontalLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbAcaSupprSelectNom.sizePolicy().hasHeightForWidth())
        self.BDcbAcaSupprSelectNom.setSizePolicy(sizePolicy)
        self.BDcbAcaSupprSelectNom.setObjectName("BDcbAcaSupprSelectNom")
        self.horizontalLayout_52.addWidget(self.BDcbAcaSupprSelectNom)
        self.verticalLayout_11.addLayout(self.horizontalLayout_52)
        self.BDpbAcaSupprValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_16)
        self.BDpbAcaSupprValid.setObjectName("BDpbAcaSupprValid")
        self.verticalLayout_11.addWidget(self.BDpbAcaSupprValid)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.label_102 = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.label_102.setObjectName("label_102")
        self.verticalLayout_11.addWidget(self.label_102)
        self.horizontalLayout_36.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(10, 10, 611, 531))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_92 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_92.sizePolicy().hasHeightForWidth())
        self.label_92.setSizePolicy(sizePolicy)
        self.label_92.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_92.setFont(font)
        self.label_92.setObjectName("label_92")
        self.horizontalLayout_32.addWidget(self.label_92)
        self.BDcbEteAcaSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbEteAcaSelect.sizePolicy().hasHeightForWidth())
        self.BDcbEteAcaSelect.setSizePolicy(sizePolicy)
        self.BDcbEteAcaSelect.setObjectName("BDcbEteAcaSelect")
        self.horizontalLayout_32.addWidget(self.BDcbEteAcaSelect)
        self.verticalLayout_8.addLayout(self.horizontalLayout_32)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.horizontalLayout_28.addLayout(self.verticalLayout_8)
        self.line_6 = QtWidgets.QFrame(self.horizontalLayoutWidget_15)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_28.addWidget(self.line_6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem6)
        self.label_134 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_134.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_134.setFont(font)
        self.label_134.setObjectName("label_134")
        self.verticalLayout_9.addWidget(self.label_134)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_139 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_139.setMinimumSize(QtCore.QSize(110, 0))
        self.label_139.setObjectName("label_139")
        self.horizontalLayout_37.addWidget(self.label_139)
        self.BDleEteAjoutNom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        self.BDleEteAjoutNom.setObjectName("BDleEteAjoutNom")
        self.horizontalLayout_37.addWidget(self.BDleEteAjoutNom)
        self.verticalLayout_9.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_140 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_140.setMinimumSize(QtCore.QSize(110, 0))
        self.label_140.setObjectName("label_140")
        self.horizontalLayout_38.addWidget(self.label_140)
        self.BDleEteAjoutAdres = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        self.BDleEteAjoutAdres.setObjectName("BDleEteAjoutAdres")
        self.horizontalLayout_38.addWidget(self.BDleEteAjoutAdres)
        self.verticalLayout_9.addLayout(self.horizontalLayout_38)
        self.BDpbEteAjoutValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_15)
        self.BDpbEteAjoutValid.setObjectName("BDpbEteAjoutValid")
        self.verticalLayout_9.addWidget(self.BDpbEteAjoutValid)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.label_142 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_142.setFont(font)
        self.label_142.setObjectName("label_142")
        self.verticalLayout_9.addWidget(self.label_142)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_143 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_143.setMinimumSize(QtCore.QSize(110, 0))
        self.label_143.setObjectName("label_143")
        self.horizontalLayout_40.addWidget(self.label_143)
        self.BDcbEteModifSelectNom = QtWidgets.QComboBox(self.horizontalLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbEteModifSelectNom.sizePolicy().hasHeightForWidth())
        self.BDcbEteModifSelectNom.setSizePolicy(sizePolicy)
        self.BDcbEteModifSelectNom.setObjectName("BDcbEteModifSelectNom")
        self.horizontalLayout_40.addWidget(self.BDcbEteModifSelectNom)
        self.verticalLayout_9.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_146 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_146.setMinimumSize(QtCore.QSize(110, 0))
        self.label_146.setObjectName("label_146")
        self.horizontalLayout_43.addWidget(self.label_146)
        self.BDleEteModifNom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        self.BDleEteModifNom.setObjectName("BDleEteModifNom")
        self.horizontalLayout_43.addWidget(self.BDleEteModifNom)
        self.verticalLayout_9.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_144 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_144.setMinimumSize(QtCore.QSize(110, 0))
        self.label_144.setObjectName("label_144")
        self.horizontalLayout_41.addWidget(self.label_144)
        self.BDleEteModifAdres = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        self.BDleEteModifAdres.setObjectName("BDleEteModifAdres")
        self.horizontalLayout_41.addWidget(self.BDleEteModifAdres)
        self.verticalLayout_9.addLayout(self.horizontalLayout_41)
        self.BDpbEteModifValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_15)
        self.BDpbEteModifValid.setObjectName("BDpbEteModifValid")
        self.verticalLayout_9.addWidget(self.BDpbEteModifValid)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.label_157 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_157.setFont(font)
        self.label_157.setObjectName("label_157")
        self.verticalLayout_9.addWidget(self.label_157)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_160 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_160.setMinimumSize(QtCore.QSize(110, 0))
        self.label_160.setObjectName("label_160")
        self.horizontalLayout_54.addWidget(self.label_160)
        self.BDcbEteModifSupprNom = QtWidgets.QComboBox(self.horizontalLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbEteModifSupprNom.sizePolicy().hasHeightForWidth())
        self.BDcbEteModifSupprNom.setSizePolicy(sizePolicy)
        self.BDcbEteModifSupprNom.setObjectName("BDcbEteModifSupprNom")
        self.horizontalLayout_54.addWidget(self.BDcbEteModifSupprNom)
        self.verticalLayout_9.addLayout(self.horizontalLayout_54)
        self.BDpbEteSupprValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_15)
        self.BDpbEteSupprValid.setObjectName("BDpbEteSupprValid")
        self.verticalLayout_9.addWidget(self.BDpbEteSupprValid)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem9)
        self.label_101 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_101.setObjectName("label_101")
        self.verticalLayout_9.addWidget(self.label_101)
        self.horizontalLayout_28.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(10, 10, 611, 531))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_91 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_91.sizePolicy().hasHeightForWidth())
        self.label_91.setSizePolicy(sizePolicy)
        self.label_91.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.horizontalLayout_18.addWidget(self.label_91)
        self.BDcbClaAcaSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbClaAcaSelect.sizePolicy().hasHeightForWidth())
        self.BDcbClaAcaSelect.setSizePolicy(sizePolicy)
        self.BDcbClaAcaSelect.setObjectName("BDcbClaAcaSelect")
        self.horizontalLayout_18.addWidget(self.BDcbClaAcaSelect)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_118 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_118.sizePolicy().hasHeightForWidth())
        self.label_118.setSizePolicy(sizePolicy)
        self.label_118.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_118.setFont(font)
        self.label_118.setObjectName("label_118")
        self.horizontalLayout_27.addWidget(self.label_118)
        self.BDcbClaEteSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_14)
        self.BDcbClaEteSelect.setObjectName("BDcbClaEteSelect")
        self.horizontalLayout_27.addWidget(self.BDcbClaEteSelect)
        self.verticalLayout_5.addLayout(self.horizontalLayout_27)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.horizontalLayout_17.addLayout(self.verticalLayout_5)
        self.line_5 = QtWidgets.QFrame(self.horizontalLayoutWidget_14)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_17.addWidget(self.line_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem12)
        self.label_130 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_130.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_130.setFont(font)
        self.label_130.setObjectName("label_130")
        self.verticalLayout_7.addWidget(self.label_130)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_131 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_131.setMinimumSize(QtCore.QSize(110, 0))
        self.label_131.setObjectName("label_131")
        self.horizontalLayout_29.addWidget(self.label_131)
        self.BDleClaAjoutNom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        self.BDleClaAjoutNom.setObjectName("BDleClaAjoutNom")
        self.horizontalLayout_29.addWidget(self.BDleClaAjoutNom)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_133 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_133.setMinimumSize(QtCore.QSize(110, 0))
        self.label_133.setObjectName("label_133")
        self.horizontalLayout_31.addWidget(self.label_133)
        self.BDleClaAjoutAn = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        self.BDleClaAjoutAn.setObjectName("BDleClaAjoutAn")
        self.horizontalLayout_31.addWidget(self.BDleClaAjoutAn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_132 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_132.setMinimumSize(QtCore.QSize(110, 0))
        self.label_132.setObjectName("label_132")
        self.horizontalLayout_30.addWidget(self.label_132)
        self.BDleClaAjoutProf = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        self.BDleClaAjoutProf.setObjectName("BDleClaAjoutProf")
        self.horizontalLayout_30.addWidget(self.BDleClaAjoutProf)
        self.verticalLayout_7.addLayout(self.horizontalLayout_30)
        self.BDpbClaAjoutValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.BDpbClaAjoutValid.setObjectName("BDpbClaAjoutValid")
        self.verticalLayout_7.addWidget(self.BDpbClaAjoutValid)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem13)
        self.label_135 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_135.setFont(font)
        self.label_135.setObjectName("label_135")
        self.verticalLayout_7.addWidget(self.label_135)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_136 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_136.setMinimumSize(QtCore.QSize(110, 0))
        self.label_136.setObjectName("label_136")
        self.horizontalLayout_33.addWidget(self.label_136)
        self.BDcbClaModifSelectNom = QtWidgets.QComboBox(self.horizontalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbClaModifSelectNom.sizePolicy().hasHeightForWidth())
        self.BDcbClaModifSelectNom.setSizePolicy(sizePolicy)
        self.BDcbClaModifSelectNom.setObjectName("BDcbClaModifSelectNom")
        self.horizontalLayout_33.addWidget(self.BDcbClaModifSelectNom)
        self.verticalLayout_7.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label.setMinimumSize(QtCore.QSize(110, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_39.addWidget(self.label)
        self.BDleClaModifNom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        self.BDleClaModifNom.setObjectName("BDleClaModifNom")
        self.horizontalLayout_39.addWidget(self.BDleClaModifNom)
        self.verticalLayout_7.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_138 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_138.setMinimumSize(QtCore.QSize(110, 0))
        self.label_138.setObjectName("label_138")
        self.horizontalLayout_35.addWidget(self.label_138)
        self.BDleClaModifAn = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        self.BDleClaModifAn.setObjectName("BDleClaModifAn")
        self.horizontalLayout_35.addWidget(self.BDleClaModifAn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_137 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_137.setMinimumSize(QtCore.QSize(110, 0))
        self.label_137.setObjectName("label_137")
        self.horizontalLayout_34.addWidget(self.label_137)
        self.BDleClaModifProf = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        self.BDleClaModifProf.setObjectName("BDleClaModifProf")
        self.horizontalLayout_34.addWidget(self.BDleClaModifProf)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        self.BDpbClaModifValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.BDpbClaModifValid.setObjectName("BDpbClaModifValid")
        self.verticalLayout_7.addWidget(self.BDpbClaModifValid)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem14)
        self.label_161 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_161.setFont(font)
        self.label_161.setObjectName("label_161")
        self.verticalLayout_7.addWidget(self.label_161)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_163 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_163.setMinimumSize(QtCore.QSize(110, 0))
        self.label_163.setObjectName("label_163")
        self.horizontalLayout_55.addWidget(self.label_163)
        self.BDcbClaSupprSelectNom = QtWidgets.QComboBox(self.horizontalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbClaSupprSelectNom.sizePolicy().hasHeightForWidth())
        self.BDcbClaSupprSelectNom.setSizePolicy(sizePolicy)
        self.BDcbClaSupprSelectNom.setObjectName("BDcbClaSupprSelectNom")
        self.horizontalLayout_55.addWidget(self.BDcbClaSupprSelectNom)
        self.verticalLayout_7.addLayout(self.horizontalLayout_55)
        self.BDpbClaSupprValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_14)
        self.BDpbClaSupprValid.setObjectName("BDpbClaSupprValid")
        self.verticalLayout_7.addWidget(self.BDpbClaSupprValid)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem15)
        self.label_100 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_100.setObjectName("label_100")
        self.verticalLayout_7.addWidget(self.label_100)
        self.horizontalLayout_17.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(10, 10, 611, 531))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem16 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem16)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_90 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_90.sizePolicy().hasHeightForWidth())
        self.label_90.setSizePolicy(sizePolicy)
        self.label_90.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_90.setFont(font)
        self.label_90.setObjectName("label_90")
        self.horizontalLayout_14.addWidget(self.label_90)
        self.BDcbEleAcaSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbEleAcaSelect.sizePolicy().hasHeightForWidth())
        self.BDcbEleAcaSelect.setSizePolicy(sizePolicy)
        self.BDcbEleAcaSelect.setObjectName("BDcbEleAcaSelect")
        self.horizontalLayout_14.addWidget(self.BDcbEleAcaSelect)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_116 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_116.sizePolicy().hasHeightForWidth())
        self.label_116.setSizePolicy(sizePolicy)
        self.label_116.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_116.setFont(font)
        self.label_116.setObjectName("label_116")
        self.horizontalLayout_15.addWidget(self.label_116)
        self.BDcbEleEtaSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_13)
        self.BDcbEleEtaSelect.setObjectName("BDcbEleEtaSelect")
        self.horizontalLayout_15.addWidget(self.BDcbEleEtaSelect)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_117 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_117.sizePolicy().hasHeightForWidth())
        self.label_117.setSizePolicy(sizePolicy)
        self.label_117.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_117.setFont(font)
        self.label_117.setObjectName("label_117")
        self.horizontalLayout_16.addWidget(self.label_117)
        self.BDcbEleClaSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_13)
        self.BDcbEleClaSelect.setObjectName("BDcbEleClaSelect")
        self.horizontalLayout_16.addWidget(self.BDcbEleClaSelect)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem17)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.line_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_13)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_13.addWidget(self.line_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem18 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem18)
        self.label_120 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_120.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_120.setFont(font)
        self.label_120.setObjectName("label_120")
        self.verticalLayout_6.addWidget(self.label_120)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_121 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_121.setMinimumSize(QtCore.QSize(110, 0))
        self.label_121.setObjectName("label_121")
        self.horizontalLayout_19.addWidget(self.label_121)
        self.BDleEleAjoutNom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.BDleEleAjoutNom.setObjectName("BDleEleAjoutNom")
        self.horizontalLayout_19.addWidget(self.BDleEleAjoutNom)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_122 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_122.setMinimumSize(QtCore.QSize(110, 0))
        self.label_122.setObjectName("label_122")
        self.horizontalLayout_20.addWidget(self.label_122)
        self.BDleEleAjoutPrenom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.BDleEleAjoutPrenom.setObjectName("BDleEleAjoutPrenom")
        self.horizontalLayout_20.addWidget(self.BDleEleAjoutPrenom)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_128 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_128.setMinimumSize(QtCore.QSize(110, 0))
        self.label_128.setObjectName("label_128")
        self.horizontalLayout_25.addWidget(self.label_128)
        self.BDleEleAjoutAdres = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.BDleEleAjoutAdres.setObjectName("BDleEleAjoutAdres")
        self.horizontalLayout_25.addWidget(self.BDleEleAjoutAdres)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_123 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_123.setMinimumSize(QtCore.QSize(110, 0))
        self.label_123.setObjectName("label_123")
        self.horizontalLayout_21.addWidget(self.label_123)
        self.BDleEleAjoutApp = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.BDleEleAjoutApp.setObjectName("BDleEleAjoutApp")
        self.horizontalLayout_21.addWidget(self.BDleEleAjoutApp)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.BDpbEleAjoutValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.BDpbEleAjoutValid.setObjectName("BDpbEleAjoutValid")
        self.verticalLayout_6.addWidget(self.BDpbEleAjoutValid)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem19)
        self.label_124 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_124.setFont(font)
        self.label_124.setObjectName("label_124")
        self.verticalLayout_6.addWidget(self.label_124)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_125 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_125.setMinimumSize(QtCore.QSize(110, 0))
        self.label_125.setObjectName("label_125")
        self.horizontalLayout_22.addWidget(self.label_125)
        self.BDcbEleModifSelectNom = QtWidgets.QComboBox(self.horizontalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbEleModifSelectNom.sizePolicy().hasHeightForWidth())
        self.BDcbEleModifSelectNom.setSizePolicy(sizePolicy)
        self.BDcbEleModifSelectNom.setObjectName("BDcbEleModifSelectNom")
        self.horizontalLayout_22.addWidget(self.BDcbEleModifSelectNom)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_126 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_126.setMinimumSize(QtCore.QSize(110, 0))
        self.label_126.setObjectName("label_126")
        self.horizontalLayout_23.addWidget(self.label_126)
        self.BDleEleModifNom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.BDleEleModifNom.setObjectName("BDleEleModifNom")
        self.horizontalLayout_23.addWidget(self.BDleEleModifNom)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_46.addWidget(self.label_2)
        self.BDleEleModifPrenom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.BDleEleModifPrenom.setObjectName("BDleEleModifPrenom")
        self.horizontalLayout_46.addWidget(self.BDleEleModifPrenom)
        self.verticalLayout_6.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_129 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_129.setMinimumSize(QtCore.QSize(110, 0))
        self.label_129.setObjectName("label_129")
        self.horizontalLayout_26.addWidget(self.label_129)
        self.BDleEleModifAdres = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.BDleEleModifAdres.setObjectName("BDleEleModifAdres")
        self.horizontalLayout_26.addWidget(self.BDleEleModifAdres)
        self.verticalLayout_6.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_127 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_127.setMinimumSize(QtCore.QSize(110, 0))
        self.label_127.setObjectName("label_127")
        self.horizontalLayout_24.addWidget(self.label_127)
        self.BDleEleModifApp = QtWidgets.QLineEdit(self.horizontalLayoutWidget_13)
        self.BDleEleModifApp.setObjectName("BDleEleModifApp")
        self.horizontalLayout_24.addWidget(self.BDleEleModifApp)
        self.verticalLayout_6.addLayout(self.horizontalLayout_24)
        self.BDpbEleModifValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.BDpbEleModifValid.setObjectName("BDpbEleModifValid")
        self.verticalLayout_6.addWidget(self.BDpbEleModifValid)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem20)
        self.label_164 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_164.setFont(font)
        self.label_164.setObjectName("label_164")
        self.verticalLayout_6.addWidget(self.label_164)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_166 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_166.setMinimumSize(QtCore.QSize(110, 0))
        self.label_166.setObjectName("label_166")
        self.horizontalLayout_57.addWidget(self.label_166)
        self.BDcbEleSupprSelectNom = QtWidgets.QComboBox(self.horizontalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbEleSupprSelectNom.sizePolicy().hasHeightForWidth())
        self.BDcbEleSupprSelectNom.setSizePolicy(sizePolicy)
        self.BDcbEleSupprSelectNom.setObjectName("BDcbEleSupprSelectNom")
        self.horizontalLayout_57.addWidget(self.BDcbEleSupprSelectNom)
        self.verticalLayout_6.addLayout(self.horizontalLayout_57)
        self.BDpbEleSupprValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_13)
        self.BDpbEleSupprValid.setObjectName("BDpbEleSupprValid")
        self.verticalLayout_6.addWidget(self.BDpbEleSupprValid)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem21)
        self.label_99 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_99.setObjectName("label_99")
        self.verticalLayout_6.addWidget(self.label_99)
        self.horizontalLayout_13.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.tab_5)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(10, 10, 611, 531))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem22 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem22)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_89 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_89.sizePolicy().hasHeightForWidth())
        self.label_89.setSizePolicy(sizePolicy)
        self.label_89.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_89.setFont(font)
        self.label_89.setObjectName("label_89")
        self.horizontalLayout.addWidget(self.label_89)
        self.BDcbMatAcaSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbMatAcaSelect.sizePolicy().hasHeightForWidth())
        self.BDcbMatAcaSelect.setSizePolicy(sizePolicy)
        self.BDcbMatAcaSelect.setObjectName("BDcbMatAcaSelect")
        self.horizontalLayout.addWidget(self.BDcbMatAcaSelect)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_112 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_112.sizePolicy().hasHeightForWidth())
        self.label_112.setSizePolicy(sizePolicy)
        self.label_112.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_112.setFont(font)
        self.label_112.setObjectName("label_112")
        self.horizontalLayout_2.addWidget(self.label_112)
        self.BDcbMatEtaSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_12)
        self.BDcbMatEtaSelect.setObjectName("BDcbMatEtaSelect")
        self.horizontalLayout_2.addWidget(self.BDcbMatEtaSelect)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_113 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_113.sizePolicy().hasHeightForWidth())
        self.label_113.setSizePolicy(sizePolicy)
        self.label_113.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_113.setFont(font)
        self.label_113.setObjectName("label_113")
        self.horizontalLayout_3.addWidget(self.label_113)
        self.BDcbMatClaSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_12)
        self.BDcbMatClaSelect.setObjectName("BDcbMatClaSelect")
        self.horizontalLayout_3.addWidget(self.BDcbMatClaSelect)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_150 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_150.sizePolicy().hasHeightForWidth())
        self.label_150.setSizePolicy(sizePolicy)
        self.label_150.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_150.setFont(font)
        self.label_150.setObjectName("label_150")
        self.horizontalLayout_4.addWidget(self.label_150)
        self.BDcbMatEleNoSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_12)
        self.BDcbMatEleNoSelect.setObjectName("BDcbMatEleNoSelect")
        self.horizontalLayout_4.addWidget(self.BDcbMatEleNoSelect)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem23)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.horizontalLayoutWidget_12)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_12.addWidget(self.line_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem24 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem24)
        self.label_107 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_107.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_107.setFont(font)
        self.label_107.setObjectName("label_107")
        self.verticalLayout_3.addWidget(self.label_107)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_115 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_115.setMinimumSize(QtCore.QSize(100, 0))
        self.label_115.setObjectName("label_115")
        self.horizontalLayout_11.addWidget(self.label_115)
        self.BDleMatAjoutNom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.BDleMatAjoutNom.setObjectName("BDleMatAjoutNom")
        self.horizontalLayout_11.addWidget(self.BDleMatAjoutNom)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_106 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_106.setMinimumSize(QtCore.QSize(100, 0))
        self.label_106.setObjectName("label_106")
        self.horizontalLayout_10.addWidget(self.label_106)
        self.BDdsbMatAjoutCoef = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDdsbMatAjoutCoef.sizePolicy().hasHeightForWidth())
        self.BDdsbMatAjoutCoef.setSizePolicy(sizePolicy)
        self.BDdsbMatAjoutCoef.setObjectName("BDdsbMatAjoutCoef")
        self.horizontalLayout_10.addWidget(self.BDdsbMatAjoutCoef)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_114 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_114.setMinimumSize(QtCore.QSize(100, 0))
        self.label_114.setObjectName("label_114")
        self.horizontalLayout_9.addWidget(self.label_114)
        self.BDleMatAjoutApp = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.BDleMatAjoutApp.setObjectName("BDleMatAjoutApp")
        self.horizontalLayout_9.addWidget(self.BDleMatAjoutApp)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.BDpbMatAjoutValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.BDpbMatAjoutValid.setObjectName("BDpbMatAjoutValid")
        self.verticalLayout_3.addWidget(self.BDpbMatAjoutValid)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem25)
        self.label_108 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_108.setFont(font)
        self.label_108.setObjectName("label_108")
        self.verticalLayout_3.addWidget(self.label_108)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_104 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_104.setMinimumSize(QtCore.QSize(100, 0))
        self.label_104.setObjectName("label_104")
        self.horizontalLayout_6.addWidget(self.label_104)
        self.BDcbMatModifSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbMatModifSelect.sizePolicy().hasHeightForWidth())
        self.BDcbMatModifSelect.setSizePolicy(sizePolicy)
        self.BDcbMatModifSelect.setObjectName("BDcbMatModifSelect")
        self.horizontalLayout_6.addWidget(self.BDcbMatModifSelect)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_151 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_151.setMinimumSize(QtCore.QSize(100, 0))
        self.label_151.setObjectName("label_151")
        self.horizontalLayout_47.addWidget(self.label_151)
        self.BDleMatModifNom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDleMatModifNom.sizePolicy().hasHeightForWidth())
        self.BDleMatModifNom.setSizePolicy(sizePolicy)
        self.BDleMatModifNom.setObjectName("BDleMatModifNom")
        self.horizontalLayout_47.addWidget(self.BDleMatModifNom)
        self.verticalLayout_3.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_105 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_105.setMinimumSize(QtCore.QSize(100, 0))
        self.label_105.setObjectName("label_105")
        self.horizontalLayout_7.addWidget(self.label_105)
        self.BDdsbMatModifCoef = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDdsbMatModifCoef.sizePolicy().hasHeightForWidth())
        self.BDdsbMatModifCoef.setSizePolicy(sizePolicy)
        self.BDdsbMatModifCoef.setObjectName("BDdsbMatModifCoef")
        self.horizontalLayout_7.addWidget(self.BDdsbMatModifCoef)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_110 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_110.setMinimumSize(QtCore.QSize(100, 0))
        self.label_110.setObjectName("label_110")
        self.horizontalLayout_8.addWidget(self.label_110)
        self.BDleMatModifApp = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.BDleMatModifApp.setObjectName("BDleMatModifApp")
        self.horizontalLayout_8.addWidget(self.BDleMatModifApp)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.BDpbMatModifValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.BDpbMatModifValid.setObjectName("BDpbMatModifValid")
        self.verticalLayout_3.addWidget(self.BDpbMatModifValid)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem26)
        self.label_119 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_119.setFont(font)
        self.label_119.setObjectName("label_119")
        self.verticalLayout_3.addWidget(self.label_119)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_168 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_168.setMinimumSize(QtCore.QSize(100, 0))
        self.label_168.setObjectName("label_168")
        self.horizontalLayout_59.addWidget(self.label_168)
        self.BDcbMatSupprSelect = QtWidgets.QComboBox(self.horizontalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BDcbMatSupprSelect.sizePolicy().hasHeightForWidth())
        self.BDcbMatSupprSelect.setSizePolicy(sizePolicy)
        self.BDcbMatSupprSelect.setObjectName("BDcbMatSupprSelect")
        self.horizontalLayout_59.addWidget(self.BDcbMatSupprSelect)
        self.verticalLayout_3.addLayout(self.horizontalLayout_59)
        self.BDpbMatSupprValid = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.BDpbMatSupprValid.setObjectName("BDpbMatSupprValid")
        self.verticalLayout_3.addWidget(self.BDpbMatSupprValid)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem27)
        self.label_98 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_3.addWidget(self.label_98)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_5, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Gestion des Académies, Etablissements, Classes et Eleves", None, -1))
        self.label_141.setText(QtWidgets.QApplication.translate("Form", "Ajout Académie", None, -1))
        self.label_145.setText(QtWidgets.QApplication.translate("Form", "Nom *", None, -1))
        self.BDpbAcaAjoutValid.setText(QtWidgets.QApplication.translate("Form", "Valider ajout Académie", None, -1))
        self.label_147.setText(QtWidgets.QApplication.translate("Form", "Modification Académie", None, -1))
        self.label_148.setText(QtWidgets.QApplication.translate("Form", "Académie à modifier *", None, -1))
        self.label_149.setText(QtWidgets.QApplication.translate("Form", "Nouveau Nom *", None, -1))
        self.BDpbAcaModifValid.setText(QtWidgets.QApplication.translate("Form", "Valider modification Académie", None, -1))
        self.label_156.setText(QtWidgets.QApplication.translate("Form", "Suppression Académie", None, -1))
        self.label_158.setText(QtWidgets.QApplication.translate("Form", "Nom *", None, -1))
        self.BDpbAcaSupprValid.setText(QtWidgets.QApplication.translate("Form", "Supprimer Académie", None, -1))
        self.label_102.setText(QtWidgets.QApplication.translate("Form", "* Champs obligatoires", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("Form", "Ajout/Modif Académie", None, -1))
        self.label_92.setText(QtWidgets.QApplication.translate("Form", "Académie", None, -1))
        self.label_134.setText(QtWidgets.QApplication.translate("Form", "Ajout Etablissement", None, -1))
        self.label_139.setText(QtWidgets.QApplication.translate("Form", "Nom *", None, -1))
        self.label_140.setText(QtWidgets.QApplication.translate("Form", "Adresse", None, -1))
        self.BDpbEteAjoutValid.setText(QtWidgets.QApplication.translate("Form", "Valider ajout Etablissement", None, -1))
        self.label_142.setText(QtWidgets.QApplication.translate("Form", "Modification Etablissement", None, -1))
        self.label_143.setText(QtWidgets.QApplication.translate("Form", "Etablissement à modifier  *", None, -1))
        self.label_146.setText(QtWidgets.QApplication.translate("Form", "Nouveau Nom*", None, -1))
        self.label_144.setText(QtWidgets.QApplication.translate("Form", "Adresse", None, -1))
        self.BDpbEteModifValid.setText(QtWidgets.QApplication.translate("Form", "Valider modification Etablissement", None, -1))
        self.label_157.setText(QtWidgets.QApplication.translate("Form", "Suppression Etablissement", None, -1))
        self.label_160.setText(QtWidgets.QApplication.translate("Form", "Nom *", None, -1))
        self.BDpbEteSupprValid.setText(QtWidgets.QApplication.translate("Form", "Supprimer Etablissement", None, -1))
        self.label_101.setText(QtWidgets.QApplication.translate("Form", "* Champs obligatoires", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("Form", "Ajout/Modif Etablissement", None, -1))
        self.label_91.setText(QtWidgets.QApplication.translate("Form", "Académie", None, -1))
        self.label_118.setText(QtWidgets.QApplication.translate("Form", "Etablissement", None, -1))
        self.label_130.setText(QtWidgets.QApplication.translate("Form", "Ajout Classe", None, -1))
        self.label_131.setText(QtWidgets.QApplication.translate("Form", "Nom *", None, -1))
        self.label_133.setText(QtWidgets.QApplication.translate("Form", "Année scolaire *", None, -1))
        self.label_132.setText(QtWidgets.QApplication.translate("Form", "Professeur Principal", None, -1))
        self.BDpbClaAjoutValid.setText(QtWidgets.QApplication.translate("Form", "Valider ajout Classe", None, -1))
        self.label_135.setText(QtWidgets.QApplication.translate("Form", "Modification Classe", None, -1))
        self.label_136.setText(QtWidgets.QApplication.translate("Form", "Classe à modifier *", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Nouveau Nom *", None, -1))
        self.label_138.setText(QtWidgets.QApplication.translate("Form", "Année scolaire *", None, -1))
        self.label_137.setText(QtWidgets.QApplication.translate("Form", "Professeur Principal", None, -1))
        self.BDpbClaModifValid.setText(QtWidgets.QApplication.translate("Form", "Valider modification Classe", None, -1))
        self.label_161.setText(QtWidgets.QApplication.translate("Form", "Suppression Classe", None, -1))
        self.label_163.setText(QtWidgets.QApplication.translate("Form", "Nom *", None, -1))
        self.BDpbClaSupprValid.setText(QtWidgets.QApplication.translate("Form", "Supprimer Classe", None, -1))
        self.label_100.setText(QtWidgets.QApplication.translate("Form", "* Champs obligatoires", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("Form", "Ajout/Modifs Classe", None, -1))
        self.label_90.setText(QtWidgets.QApplication.translate("Form", "Académie", None, -1))
        self.label_116.setText(QtWidgets.QApplication.translate("Form", "Etablissement", None, -1))
        self.label_117.setText(QtWidgets.QApplication.translate("Form", "Classe", None, -1))
        self.label_120.setText(QtWidgets.QApplication.translate("Form", "Ajout Eleve", None, -1))
        self.label_121.setText(QtWidgets.QApplication.translate("Form", "Nom *", None, -1))
        self.label_122.setText(QtWidgets.QApplication.translate("Form", "Prénom  *", None, -1))
        self.label_128.setText(QtWidgets.QApplication.translate("Form", "Adresse", None, -1))
        self.label_123.setText(QtWidgets.QApplication.translate("Form", "Appréciation générale", None, -1))
        self.BDpbEleAjoutValid.setText(QtWidgets.QApplication.translate("Form", "Valider ajout Eleve", None, -1))
        self.label_124.setText(QtWidgets.QApplication.translate("Form", "Modification Eleve", None, -1))
        self.label_125.setText(QtWidgets.QApplication.translate("Form", "Elève à modifier *", None, -1))
        self.label_126.setText(QtWidgets.QApplication.translate("Form", "Nom *", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Prénom *", None, -1))
        self.label_129.setText(QtWidgets.QApplication.translate("Form", "Adresse", None, -1))
        self.label_127.setText(QtWidgets.QApplication.translate("Form", "Appréciation générale", None, -1))
        self.BDpbEleModifValid.setText(QtWidgets.QApplication.translate("Form", "Valider modification Eleve", None, -1))
        self.label_164.setText(QtWidgets.QApplication.translate("Form", "Suppression Eleve", None, -1))
        self.label_166.setText(QtWidgets.QApplication.translate("Form", "Elève à supprimer *", None, -1))
        self.BDpbEleSupprValid.setText(QtWidgets.QApplication.translate("Form", "Supprimer Eleve", None, -1))
        self.label_99.setText(QtWidgets.QApplication.translate("Form", "* Champs obligatoires", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("Form", "Ajout/Modif Eleve", None, -1))
        self.label_89.setText(QtWidgets.QApplication.translate("Form", "Académie", None, -1))
        self.label_112.setText(QtWidgets.QApplication.translate("Form", "Etablissement", None, -1))
        self.label_113.setText(QtWidgets.QApplication.translate("Form", "Classe", None, -1))
        self.label_150.setText(QtWidgets.QApplication.translate("Form", "Eleve", None, -1))
        self.label_107.setText(QtWidgets.QApplication.translate("Form", "Ajout Matiere", None, -1))
        self.label_115.setText(QtWidgets.QApplication.translate("Form", "Nom Matière *", None, -1))
        self.label_106.setText(QtWidgets.QApplication.translate("Form", "Coefficient  *", None, -1))
        self.label_114.setText(QtWidgets.QApplication.translate("Form", "Appréciation Matière", None, -1))
        self.BDpbMatAjoutValid.setText(QtWidgets.QApplication.translate("Form", "Valider ajout Matière", None, -1))
        self.label_108.setText(QtWidgets.QApplication.translate("Form", "Modification Matière", None, -1))
        self.label_104.setText(QtWidgets.QApplication.translate("Form", "Nom Matière *", None, -1))
        self.label_151.setText(QtWidgets.QApplication.translate("Form", "Nom  *", None, -1))
        self.label_105.setText(QtWidgets.QApplication.translate("Form", "Coefficient  *", None, -1))
        self.label_110.setText(QtWidgets.QApplication.translate("Form", "Appréciation Matière", None, -1))
        self.BDpbMatModifValid.setText(QtWidgets.QApplication.translate("Form", "Valider modification Matière", None, -1))
        self.label_119.setText(QtWidgets.QApplication.translate("Form", "Suppression Matière", None, -1))
        self.label_168.setText(QtWidgets.QApplication.translate("Form", "Nom Matière *", None, -1))
        self.BDpbMatSupprValid.setText(QtWidgets.QApplication.translate("Form", "Supprimer Matière", None, -1))
        self.label_98.setText(QtWidgets.QApplication.translate("Form", "* Champs obligatoires", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtWidgets.QApplication.translate("Form", "Ajout/Modif Matière", None, -1))

