# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/AELION/AppData/Local/Temp/PP_Design_v1GJPmiG.ui',
# licensing of 'C:/Users/AELION/AppData/Local/Temp/PP_Design_v1GJPmiG.ui' applies.
#
# Created: Mon Aug 19 16:17:59 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Editeur_de_Notes(object):
    def setupUi(self, Editeur_de_Notes):
        Editeur_de_Notes.setObjectName("Editeur_de_Notes")
        Editeur_de_Notes.resize(1196, 848)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Editeur_de_Notes)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(Editeur_de_Notes)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(Editeur_de_Notes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(30, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.cbAcademieSelect = QtWidgets.QComboBox(Editeur_de_Notes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAcademieSelect.sizePolicy().hasHeightForWidth())
        self.cbAcademieSelect.setSizePolicy(sizePolicy)
        self.cbAcademieSelect.setObjectName("cbAcademieSelect")
        self.horizontalLayout_4.addWidget(self.cbAcademieSelect)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Editeur_de_Notes)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cbEtablissementSelect = QtWidgets.QComboBox(Editeur_de_Notes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbEtablissementSelect.sizePolicy().hasHeightForWidth())
        self.cbEtablissementSelect.setSizePolicy(sizePolicy)
        self.cbEtablissementSelect.setObjectName("cbEtablissementSelect")
        self.horizontalLayout_3.addWidget(self.cbEtablissementSelect)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Editeur_de_Notes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cbClasseSelect = QtWidgets.QComboBox(Editeur_de_Notes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbClasseSelect.sizePolicy().hasHeightForWidth())
        self.cbClasseSelect.setSizePolicy(sizePolicy)
        self.cbClasseSelect.setObjectName("cbClasseSelect")
        self.horizontalLayout.addWidget(self.cbClasseSelect)
        self.horizontalLayout_10.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.pbGestionDb = QtWidgets.QPushButton(Editeur_de_Notes)
        self.pbGestionDb.setObjectName("pbGestionDb")
        self.horizontalLayout_10.addWidget(self.pbGestionDb)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem4)
        self.tabWidget = QtWidgets.QTabWidget(Editeur_de_Notes)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.twAffichageMoyennes = QtWidgets.QTableWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twAffichageMoyennes.sizePolicy().hasHeightForWidth())
        self.twAffichageMoyennes.setSizePolicy(sizePolicy)
        self.twAffichageMoyennes.setObjectName("twAffichageMoyennes")
        self.twAffichageMoyennes.setColumnCount(0)
        self.twAffichageMoyennes.setRowCount(0)
        self.twAffichageMoyennes.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_6.addWidget(self.twAffichageMoyennes)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.qRadar = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qRadar.sizePolicy().hasHeightForWidth())
        self.qRadar.setSizePolicy(sizePolicy)
        self.qRadar.setMinimumSize(QtCore.QSize(450, 0))
        self.qRadar.setScaledContents(False)
        self.qRadar.setObjectName("qRadar")
        self.verticalLayout_5.addWidget(self.qRadar)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem5)
        self.pbImpressionPdf = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbImpressionPdf.sizePolicy().hasHeightForWidth())
        self.pbImpressionPdf.setSizePolicy(sizePolicy)
        self.pbImpressionPdf.setMinimumSize(QtCore.QSize(450, 0))
        self.pbImpressionPdf.setObjectName("pbImpressionPdf")
        self.verticalLayout_5.addWidget(self.pbImpressionPdf)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem6)
        self.pbExportCsv = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbExportCsv.sizePolicy().hasHeightForWidth())
        self.pbExportCsv.setSizePolicy(sizePolicy)
        self.pbExportCsv.setMinimumSize(QtCore.QSize(450, 0))
        self.pbExportCsv.setObjectName("pbExportCsv")
        self.verticalLayout_5.addWidget(self.pbExportCsv)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 1151, 212))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_11.addWidget(self.label_18)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(130, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self.cbNoteMatiereSelect = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.cbNoteMatiereSelect.setObjectName("cbNoteMatiereSelect")
        self.horizontalLayout_16.addWidget(self.cbNoteMatiereSelect)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.label_98 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_98.sizePolicy().hasHeightForWidth())
        self.label_98.setSizePolicy(sizePolicy)
        self.label_98.setObjectName("label_98")
        self.horizontalLayout_16.addWidget(self.label_98)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkbAjoutDevoir = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbAjoutDevoir.sizePolicy().hasHeightForWidth())
        self.checkbAjoutDevoir.setSizePolicy(sizePolicy)
        self.checkbAjoutDevoir.setText("")
        self.checkbAjoutDevoir.setObjectName("checkbAjoutDevoir")
        self.horizontalLayout_7.addWidget(self.checkbAjoutDevoir)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(130, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.leNoteAjoutNom = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leNoteAjoutNom.sizePolicy().hasHeightForWidth())
        self.leNoteAjoutNom.setSizePolicy(sizePolicy)
        self.leNoteAjoutNom.setObjectName("leNoteAjoutNom")
        self.horizontalLayout_6.addWidget(self.leNoteAjoutNom)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(125, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.dsbAjoutNoteCoeff = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_6)
        self.dsbAjoutNoteCoeff.setProperty("value", 1.0)
        self.dsbAjoutNoteCoeff.setObjectName("dsbAjoutNoteCoeff")
        self.horizontalLayout_8.addWidget(self.dsbAjoutNoteCoeff)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.pbNoteAjout = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pbNoteAjout.setObjectName("pbNoteAjout")
        self.verticalLayout.addWidget(self.pbNoteAjout)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_11.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkbModifDevoir = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbModifDevoir.sizePolicy().hasHeightForWidth())
        self.checkbModifDevoir.setSizePolicy(sizePolicy)
        self.checkbModifDevoir.setText("")
        self.checkbModifDevoir.setObjectName("checkbModifDevoir")
        self.horizontalLayout_5.addWidget(self.checkbModifDevoir)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(130, 0))
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_15.addWidget(self.label_21)
        self.cbNoteModifNomSelect = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.cbNoteModifNomSelect.setObjectName("cbNoteModifNomSelect")
        self.horizontalLayout_15.addWidget(self.cbNoteModifNomSelect)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(130, 0))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.leNoteModifNom = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leNoteModifNom.sizePolicy().hasHeightForWidth())
        self.leNoteModifNom.setSizePolicy(sizePolicy)
        self.leNoteModifNom.setObjectName("leNoteModifNom")
        self.horizontalLayout_14.addWidget(self.leNoteModifNom)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_19.setMinimumSize(QtCore.QSize(125, 0))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.dsbNoteModifCoeff = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_6)
        self.dsbNoteModifCoeff.setProperty("value", 1.0)
        self.dsbNoteModifCoeff.setObjectName("dsbNoteModifCoeff")
        self.horizontalLayout_12.addWidget(self.dsbNoteModifCoeff)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.pbNoteModif = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pbNoteModif.setObjectName("pbNoteModif")
        self.verticalLayout_2.addWidget(self.pbNoteModif)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_11.addWidget(self.line_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkbSupprDevoir = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbSupprDevoir.sizePolicy().hasHeightForWidth())
        self.checkbSupprDevoir.setSizePolicy(sizePolicy)
        self.checkbSupprDevoir.setText("")
        self.checkbSupprDevoir.setObjectName("checkbSupprDevoir")
        self.horizontalLayout_9.addWidget(self.checkbSupprDevoir)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(130, 0))
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.cbNoteSupprNomSelect = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.cbNoteSupprNomSelect.setObjectName("cbNoteSupprNomSelect")
        self.horizontalLayout_19.addWidget(self.cbNoteSupprNomSelect)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem12)
        self.pbNoteSuppr = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pbNoteSuppr.setObjectName("pbNoteSuppr")
        self.verticalLayout_7.addWidget(self.pbNoteSuppr)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 230, 1151, 461))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_6)
        self.groupBox.setObjectName("groupBox")
        self.twAffichageNote = QtWidgets.QTableWidget(self.groupBox)
        self.twAffichageNote.setGeometry(QtCore.QRect(10, 20, 741, 431))
        self.twAffichageNote.setObjectName("twAffichageNote")
        self.twAffichageNote.setColumnCount(0)
        self.twAffichageNote.setRowCount(0)
        self.gbAjoutNote = QtWidgets.QGroupBox(self.groupBox)
        self.gbAjoutNote.setGeometry(QtCore.QRect(760, 0, 381, 459))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbAjoutNote.sizePolicy().hasHeightForWidth())
        self.gbAjoutNote.setSizePolicy(sizePolicy)
        self.gbAjoutNote.setObjectName("gbAjoutNote")
        self.twSaisieNote = QtWidgets.QTableWidget(self.gbAjoutNote)
        self.twSaisieNote.setGeometry(QtCore.QRect(10, 20, 361, 431))
        self.twSaisieNote.setObjectName("twSaisieNote")
        self.twSaisieNote.setColumnCount(0)
        self.twSaisieNote.setRowCount(0)
        self.horizontalLayout_17.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_4.addWidget(self.tabWidget)

        self.retranslateUi(Editeur_de_Notes)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Editeur_de_Notes)

    def retranslateUi(self, Editeur_de_Notes):
        Editeur_de_Notes.setWindowTitle(QtWidgets.QApplication.translate("Editeur_de_Notes", "Form", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Editeur de notes", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Académie", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Etablissement", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Classe", None, -1))
        self.pbGestionDb.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Gestion des Académies, Etablissements, Classes, Eleves et Matières", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Moyenne par Elève par Matière", None, -1))
        self.qRadar.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "  ", None, -1))
        self.pbImpressionPdf.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Impression Bulletin pdf", None, -1))
        self.pbExportCsv.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Exporter les notes en csv", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("Editeur_de_Notes", "Affichage des Moyennes par Matière", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Sélection de la Matière", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Matière *", None, -1))
        self.label_98.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "* Champs obligatoires", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Ajout devoir", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Nom du devoir *", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Coefficient du devoir *", None, -1))
        self.pbNoteAjout.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Ajout", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Modification devoir", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Nom du devoir *", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Nouveau nom du devoir *", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Coefficient du devoir *", None, -1))
        self.pbNoteModif.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Modification", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Suppression devoir", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Nom du devoir *", None, -1))
        self.pbNoteSuppr.setText(QtWidgets.QApplication.translate("Editeur_de_Notes", "Suppression", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Editeur_de_Notes", "Affichage des élèves et devoirs", None, -1))
        self.gbAjoutNote.setTitle(QtWidgets.QApplication.translate("Editeur_de_Notes", "Ajout de Notes", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("Editeur_de_Notes", "Saisie des Notes", None, -1))

